using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QBits.Intuition.AbstractLanguageIntelligence.Model.Brains
{
    /// <summary>
    /// Neuryt, akson (axon)- element neuronu odpowiedzialny za przekazywanie informacji z ciała komórki do kolejnych neuronów lub komórek efektorowych
    /// (np. komórek mięśniowych bądź gruczołowych).
    /// Neuryt może być osłonięty osłonką włókien nerwowych.
    /// Jest z reguły dłuższy od dendrytów i w odróżnieniu od nich, w komórce występuje pojedynczo (choć może być rozgałęziony).
    /// <para/>http://pl.wikipedia.org/wiki/Neuryt
    /// </summary>
    public class Axon
    {
        #region Public members
        /// <summary>
        /// Cell that owns this axon.
        /// </summary>
        public Neuron ParentCell { get; private set; }

        /// <summary>
        /// Target for the signal from this axon.
        /// </summary>
        public Dendrite? SignalTarget { get; internal set; }

        /// <summary>
        /// Event that is raised when this axon gets excited.
        /// </summary>
        public static event EventHandler? AxonExcited;
        #endregion

        #region Public API
        /// <summary>
        /// Creates new instance of Axon that belongs to the indicated parent cell.
        /// </summary>
        /// <param name="parentCell">Parent cell (usually the caller) that creates this axon.</param>
        internal Axon(Neuron parentCell)
        {
            ParentCell = parentCell;
            if (parentCell == null) throw new ArgumentNullException("parentCell", "parentCell is null.");
        }

        /// <summary>
        /// Provides easy to read description of this axon.
        /// </summary>
        public override string ToString()
        {
            return string.Format("Parent={0}", ParentCell);
        }

        /// <summary>
        /// Called from the parent neuron cell. Excites the axon with the signal generated by the neuron.
        /// This causes the signal to be passed to the receiving dendrite.
        /// </summary>
        /// <param name="signal">Signal to be applied to this cell.</param>
        public void Excite(double signal)
        {
            OnAxonExcited();

            if (SignalTarget == null)
            {
                throw new InvalidOperationException("SignalTarget is null. Cannot excite a null target.");
            }
            SignalTarget.Excite(signal);
        }
        #endregion

        /// <summary>
        /// Called when this axon has been excited. Raises the event.
        /// </summary>
        void OnAxonExcited()
        {
            if (AxonExcited != null) AxonExcited(this, EventArgs.Empty);
        }
    }
}
